<a name="SelectionHandle"></a>

## SelectionHandle
Use this class to read and write (and listen for changes to) the selection
for a Crosstalk group. This is intended to be used for linked brushing.

If two (or more) `SelectionHandle` instances in the same webpage share the
same group name, they will share the same state. Setting the selection using
one `SelectionHandle` instance will result in the `value` property instantly
changing across the others, and `"change"` event listeners on all instances
(including the one that initiated the sending) will fire.

**Kind**: global class  

* [SelectionHandle](#SelectionHandle)
    * [new crosstalk.SelectionHandle([group], [extraInfo])](#new_SelectionHandle_new)
    * _instance_
        * [.value](#SelectionHandle+value)
        * [.setGroup(group)](#SelectionHandle+setGroup)
        * [.set(selectedKeys, [extraInfo])](#SelectionHandle+set)
        * [.clear([extraInfo])](#SelectionHandle+clear)
        * [.on(eventType, listener)](#SelectionHandle+on) ⇒ <code>string</code>
        * [.off(eventType, listener)](#SelectionHandle+off)
        * [.close()](#SelectionHandle+close)
        * ["change"](#SelectionHandle+event_change)
    * _inner_
        * [~listener](#SelectionHandle..listener) : <code>function</code>

<a name="new_SelectionHandle_new"></a>

### new crosstalk.SelectionHandle([group], [extraInfo])

| Param | Type | Description |
| ------------- | ------------- | ------------- |
| [group] | <code>string</code> | The name of the Crosstalk group, or if none,   null or undefined (or any other falsy value). This can be changed later   via the [SelectionHandle#setGroup](#setGroup) method. |
| [extraInfo] | <code>Object</code> | An object whose properties will be copied to   the event object whenever an event is emitted. |

<a name="SelectionHandle+value"></a>

### selectionHandle.value
Retrieves the current selection for the group represented by this
`SelectionHandle`.

- If no selection is active, then this value will be falsy.
- If a selection is active, but no data points are selected, then this
  value will be an empty array.
- If a selection is active, and data points are selected, then the keys
  of the selected data points will be present in the array.

**Kind**: instance property of [<code>SelectionHandle</code>](#SelectionHandle)  
<a name="SelectionHandle+setGroup"></a>

### selectionHandle.setGroup(group)
Changes the Crosstalk group membership of this SelectionHandle. The group
being switched away from (if any) will not have its selection value
modified as a result of calling `setGroup`, even if this handle was the
most recent handle to set the selection of the group.

The group being switched to (if any) will also not have its selection value
modified as a result of calling `setGroup`. If you want to set the
selection value of the new group, call `set` explicitly.

**Kind**: instance method of [<code>SelectionHandle</code>](#SelectionHandle)  

| Param | Type | Description |
| ------------- | ------------- | ------------- |
| group | <code>string</code> | The name of the Crosstalk group, or null (or   undefined) to clear the group. |

<a name="SelectionHandle+set"></a>

### selectionHandle.set(selectedKeys, [extraInfo])
Overwrites the current selection for the group, and raises the `"change"`
event among all of the group's '`SelectionHandle` instances (including
this one).

**Kind**: instance method of [<code>SelectionHandle</code>](#SelectionHandle)  
**Emits**: [<code>change</code>](#SelectionHandle+event_change)  

| Param | Type | Description |
| ------------- | ------------- | ------------- |
| selectedKeys | <code>[ &#x27;Array&#x27; ].&lt;string&gt;</code> | Falsy, empty array, or array of keys (see   [value](#SelectionHandle+value)). |
| [extraInfo] | <code>Object</code> | Extra properties to be included on the event   object that's passed to listeners (in addition to any options that were   passed into the `SelectionHandle` constructor). |

<a name="SelectionHandle+clear"></a>

### selectionHandle.clear([extraInfo])
Overwrites the current selection for the group, and raises the `"change"`
event among all of the group's '`SelectionHandle` instances (including
this one).

**Kind**: instance method of [<code>SelectionHandle</code>](#SelectionHandle)  
**Emits**: [<code>change</code>](#SelectionHandle+event_change)  

| Param | Type | Description |
| ------------- | ------------- | ------------- |
| [extraInfo] | <code>Object</code> | Extra properties to be included on the event   object that's passed to listeners (in addition to any that were passed   into the `SelectionHandle` constructor). |

<a name="SelectionHandle+on"></a>

### selectionHandle.on(eventType, listener) ⇒ <code>string</code>
Subscribes to events on this `SelectionHandle`.

**Kind**: instance method of [<code>SelectionHandle</code>](#SelectionHandle)  
**Returns**: <code>string</code> - - A token to pass to [off](#SelectionHandle+off) to cancel
  this subscription.  

| Param | Type | Description |
| ------------- | ------------- | ------------- |
| eventType | <code>string</code> | Indicates the type of events to listen to.   Currently, only `"change"` is supported. |
| listener | [<code>listener</code>](#SelectionHandle..listener) | The callback function that   will be invoked when the event occurs. |

<a name="SelectionHandle+off"></a>

### selectionHandle.off(eventType, listener)
Cancels event subscriptions created by [on](#SelectionHandle+on).

**Kind**: instance method of [<code>SelectionHandle</code>](#SelectionHandle)  

| Param | Type | Description |
| ------------- | ------------- | ------------- |
| eventType | <code>string</code> | The type of event to unsubscribe. |
| listener | <code>string</code> \| [<code>listener</code>](#SelectionHandle..listener) | Either the callback   function previously passed into [on](#SelectionHandle+on), or the   string that was returned from [on](#SelectionHandle+on). |

<a name="SelectionHandle+close"></a>

### selectionHandle.close()
Shuts down the `SelectionHandle` object.

Removes all event listeners that were added through this handle.

**Kind**: instance method of [<code>SelectionHandle</code>](#SelectionHandle)  
<a name="SelectionHandle+event_change"></a>

### "change"
**Kind**: event emitted by [<code>SelectionHandle</code>](#SelectionHandle)  
**Properties**

| Name | Type | Description |
| ------------- | ------------- | ------------- |
| value | <code>object</code> | The new value of the selection, or `undefined`   if no selection is active. |
| oldValue | <code>object</code> | The previous value of the selection. |
| sender | [<code>SelectionHandle</code>](#SelectionHandle) | The `SelectionHandle` instance that   changed the value. |

<a name="SelectionHandle..listener"></a>

### SelectionHandle~listener : <code>function</code>
**Kind**: inner typedef of [<code>SelectionHandle</code>](#SelectionHandle)  

| Param | Type | Description |
| ------------- | ------------- | ------------- |
| event | <code>Object</code> | An object containing details of the event. For   `"change"` events, this includes the properties `value` (the new   value of the selection, or `undefined` if no selection is active),   `oldValue` (the previous value of the selection), and `sender` (the   `SelectionHandle` instance that made the change). |

